apiVersion: v1
kind: Service
metadata:
  name: tawazun-svc
  namespace: lama-tawazun
  labels:
    app: tawazun
    name: lamaalawwad
spec:
  type: NodePort  
  selector:
    app:  tawazun
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort:  30000
