apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: lama-tawazun
  labels:
    app: tawazun
    name: lamaalawwad
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/tmp/lab"
